/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamDebuggerRouteImport } from './routes/stream-debugger'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLoadTraceRouteImport } from './routes/api.load-trace'
import { Route as ApiListTracesRouteImport } from './routes/api.list-traces'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const StreamDebuggerRoute = StreamDebuggerRouteImport.update({
  id: '/stream-debugger',
  path: '/stream-debugger',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoadTraceRoute = ApiLoadTraceRouteImport.update({
  id: '/api/load-trace',
  path: '/api/load-trace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListTracesRoute = ApiListTracesRouteImport.update({
  id: '/api/list-traces',
  path: '/api/list-traces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stream-debugger': typeof StreamDebuggerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/list-traces': typeof ApiListTracesRoute
  '/api/load-trace': typeof ApiLoadTraceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stream-debugger': typeof StreamDebuggerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/list-traces': typeof ApiListTracesRoute
  '/api/load-trace': typeof ApiLoadTraceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stream-debugger': typeof StreamDebuggerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/list-traces': typeof ApiListTracesRoute
  '/api/load-trace': typeof ApiLoadTraceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stream-debugger'
    | '/api/chat'
    | '/api/list-traces'
    | '/api/load-trace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stream-debugger'
    | '/api/chat'
    | '/api/list-traces'
    | '/api/load-trace'
  id:
    | '__root__'
    | '/'
    | '/stream-debugger'
    | '/api/chat'
    | '/api/list-traces'
    | '/api/load-trace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StreamDebuggerRoute: typeof StreamDebuggerRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiListTracesRoute: typeof ApiListTracesRoute
  ApiLoadTraceRoute: typeof ApiLoadTraceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stream-debugger': {
      id: '/stream-debugger'
      path: '/stream-debugger'
      fullPath: '/stream-debugger'
      preLoaderRoute: typeof StreamDebuggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/load-trace': {
      id: '/api/load-trace'
      path: '/api/load-trace'
      fullPath: '/api/load-trace'
      preLoaderRoute: typeof ApiLoadTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/list-traces': {
      id: '/api/list-traces'
      path: '/api/list-traces'
      fullPath: '/api/list-traces'
      preLoaderRoute: typeof ApiListTracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StreamDebuggerRoute: StreamDebuggerRoute,
  ApiChatRoute: ApiChatRoute,
  ApiListTracesRoute: ApiListTracesRoute,
  ApiLoadTraceRoute: ApiLoadTraceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
